version: "3.9"

volumes:
  dbdata:

services:
  blog:
    build: .
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000" # port mapping host:container
  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: test_db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql # persist data to dbdata volume
    ports:
      - "3306:3306"
  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin:latest
    links:
      - db
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

